services:
  adda-backend:
    image: adda-backend
    build:
      context: .
      target: dev
      platforms:
        - linux/arm64
        - linux/amd64
    container_name: adda-backend
    env_file:
      - ./.env
    networks:
      - adda-backend-network
    volumes:
      - ./private/:/private
      - .:/app
    ports:
      - 8080:8080

networks:
  adda-backend-network:
